const data = {
  products: [
    {
      id: '1',
      name: 'strawberry-yogurt',
      slug: 'srtawberry-yogurt',
      image: '/images/strawberry.jpg',
      price: 60,
      countInStock: 10,
      rating: 4.0,
      numReviews: 10,
      description: 'made from fresh strawberries and fresh milk!',
    },
    {
      id: '2',
      name: 'soda-yogurt',
      slug: 'soda-yogurt',
      image: '/images/soda.jpg',
      price: 40,
      countInStock: 20,
      rating: 3.0,
      numReviews: 7,
      description: ' wanna have some soda in a heathier way?',
    },
    {
      id: '3',
      name: 'guava-yogurt',
      slug: 'guava-yogurt',
      image: '/images/guava.jpeg',
      price: 80,
      countInStock: 5,
      rating: 4.5,
      numReviews: 14,
      description: 'Only sold in hot summer!',
    },
    {
      id: '4',
      name: 'greek-yogurt',
      slug: 'greek-yogurt',
      image: '/images/greek.jpg',
      price: 75,
      countInStock: 8,
      rating: 5.0,
      numReviews: 9,
      description: 'Tasting yogurt like tasing ice cream?',
    },
    {
      id: '5',
      name: 'chocolate-yogurt',
      slug: 'chocolate-yogurt',
      image: '/images/chocolate.jpeg',
      price: 55,
      countInStock: 4,
      rating: 5.0,
      numReviews: 15,
      description: ' Shout out to chocoholic!',
    },
    {
      id: '6',
      name: 'berries-yogurt',
      slug: 'berries-yogurt',
      image: '/images/berries.jpg',
      price: 80,
      countInStock: 15,
      rating: 5.0,
      numReviews: 12,
      description: 'Sour-tasted and fresh freezed berries!',
    },
  ],
};
export default data;
